### ISSUE TITLE
A question about yDivs and yPatterns

### ISSUE THREAD

**Issue by WanzhuoShi** [Wenlab/BLITZ#12]
I have a problem about this function. (I am trying to make this function into two parts)
As you can see, the variable called delimY is assigned from yDivide(a property in the ScreenData).
```
int delimY = screen.allAreas[cIdx].allPatches[fishIdx].yDivide;
```
But later, when we need to judge whether the fish is in the CS area or not, it is compared with head.y. I think these two variables are from different classes. They are in different coordinate systems. 
Is it a confusion? Or I don't have a correct comprehension about this function?
@young24 
```
if (pIdx) // patternIdx == 1, since patternIdx == 2 is excluded{
        if (head.y > delimY) // In non-CS area
		allArenas[cIdx].allFish[fishIdx].lastTimeInCS = sElapsed;
}
else {
	if (head.y < delimY)
		allArenas[cIdx].allFish[fishIdx].lastTimeInCS = sElapsed;
}
```

**Comment by young24** [comment]
Can you show me which function it is?

**Comment by WanzhuoShi** [comment]
ExperimentData::updatePatternInTraining

**Comment by young24** [comment]
You are right, it has to be the 'yDiv', it might be a mistake made by me when I tried to rename some variables in FishData. Originally, the 'yDiv' was named as the 'delimY'.
@WanzhuoShi

**Comment by WanzhuoShi** [comment]
Okay, I will correct it.
