### ISSUE TITLE
idxFrame metric or time metric

### ISSUE THREAD

**Issue by young24** [Wenlab/BLITZ#13]
When using the idxFrame metric, we have to make sure that the framerate in the settings does **not** exceed the maximum framerate cameras can support. Otherwise, there would be a significant difference between the system time and the calculated time. 
In my experience, the maximum framerate cameras can support is 30 f/s when three cameras shoot simultaneously. So it is good enough for our use.
We should think about this potential issue carefully in case any unwanted problem happened in the future.
@WanzhuoShi

**Comment by WanzhuoShi** [comment]
Maybe I can create a function to test whether FRAMERATE is acceptable or not.

**Comment by young24** [comment]
I think we can leave this issue alone for now. Let's first make the three areas with different textures first.
@WanzhuoShi

**Comment by WanzhuoShi** [comment]
I have modified the "getTime" function to add the functionality of testing FRAMERATE. 
However, I am not sure this function is correct. As you said, I will test this function later and make three areas with different textures first.
@young24 
```
bool ExperimentData::getTime() {
	sElapsed = idxFrame / (FRAMERATE * numCameras);
	int systemTime = (int)expTimer.getElapsedTimeInSec();
	if (fabs(sElapsed - systemTime) > 1) {
		cout << "The FRAMERATE is not acceptable" << endl;
		return false;
	}
	msRemElapsed = (int)expTimer.getElapsedTimeInMilliSec() % 1000;
	cout << "Time: " << sElapsed << " (s) " << endl;
	return true;
}
```

**Comment by young24** [comment]
Cool, I'll test this function with you then.

**Comment by WanzhuoShi** [comment]
How about 7pm？

From my iPhone

**Comment by young24** [comment]
Okay.

**Comment by young24** [comment]
issue solved. Close.
