### ISSUE TITLE
Pylon Compatibility Issues with Visual Studio 

### ISSUE THREAD

**Issue by usmansani123** [Wenlab/BLITZ#32]
I am trying to compatible pylon 4, pylon 5 and pylon 6 with visual studio but it creates the issue while compatibility. i also select the root directory path of pylon in the visual studio but it still creates problem.

**Comment by young24** [comment]
Hi, 
Can you show the error message? If I understand correctly, you were trying to compile Pylon with visual studio right? But I think you only need a single version of Pylon instead of three. May I ask why you need three different versions of Pylon?

**Comment by usmansani123** [comment]
Hi,
I am new to Blitz. I have tried these three versions for compatibility to visual studio one by one. But all these three versions creating some problems i.e Root Directory Path. I have facing these problems.

![Capture33](https://user-images.githubusercontent.com/55784431/84868754-9df6c680-b096-11ea-8c89-7af9c11f6aba.PNG)

**Comment by young24** [comment]
Hi, I think the problem is that the Pylon path was not correctly configured.
You can try to follow [this manual](https://manualzz.com/doc/8931657/getting-started-with-pylon-5-and-opencv) to install Pylon5 with opencv. Hope it helps.

**Comment by usmansani123** [comment]
Hi, Thank you for your help. I have solved the Pylon compatibility issue with Visual Studio. But now i have these issues in the code.  

![Capture323](https://user-images.githubusercontent.com/55784431/85017557-15a31f00-b185-11ea-83fa-574e5bc39288.PNG)

**Comment by wenquan** [comment]
@CrickCrick Can you address the above question?

**Comment by young24** [comment]
> Hi, Thank you for your help. I have solved the Pylon compatibility issue with Visual Studio. But now i have these issues in the code.
> 
> ![Capture323](https://user-images.githubusercontent.com/55784431/85017557-15a31f00-b185-11ea-83fa-574e5bc39288.PNG)

The reason is simple. You didn't include Pylon libraries properly. You can check [this file](https://github.com/Wenlab/BLITZ/blob/master/MyLibs/talk2camera.h) to learn how to include Pylon libraries in your code. @usmansani123

**Comment by CrickCrick** [comment]
> Hi, Thank you for your help. I have solved the Pylon compatibility issue with Visual Studio. But now i have these issues in the code.
> 
> ![Capture323](https://user-images.githubusercontent.com/55784431/85017557-15a31f00-b185-11ea-83fa-574e5bc39288.PNG)

You need to set up python and include it in VS

**Comment by usmansani123** [comment]
@young24 and @CrickCrick 
Thank you for your help. I have changed the path according to instructions given in the link you mentioned in previous reply. somehow i am able to solve the problem but now i faced the errors given in the picture. I also want to know that there is any need to attach external camera, or basler camera to run this code.
![Capture8888](https://user-images.githubusercontent.com/55784431/85063829-26bf5080-b1c4-11ea-86d9-987741fdabc4.PNG)

**Comment by CrickCrick** [comment]
> Thank you for your help. I have changed the path according to instructions given in the link you mentioned in previous reply. somehow i am able to solve the problem but now i faced the errors given in the picture. I also want to know that there is any need to attach external camera, or basler camera to run this code.

It may be a C++ version issue, versions after C++ 11 should not have this problem. We could use some videos to test the program without using the camera.

**Comment by usmansani123** [comment]
@CrickCrick @young24 

Thanks for your time and help. I have removed many of the errors but still i faced some issues. The errors are given in the picture below. 
![Capture6365](https://user-images.githubusercontent.com/55784431/85225251-3bc8f900-b3e9-11ea-980f-d030931ee7a5.PNG)

**Comment by young24** [comment]
> @CrickCrick @young24
> 
> Thanks for your time and help. I have removed many of the errors but still i faced some issues. The errors are given in the picture below.
> ![Capture6365](https://user-images.githubusercontent.com/55784431/85225251-3bc8f900-b3e9-11ea-980f-d030931ee7a5.PNG)

Those are C++ syntax errors. You might need to learn C++ basics to modify the code. Have a look at this book: [Accelerated C++](https://www.pdfdrive.com/accelerated-c-andrew-koenig-barbara-e-moopdf-e37303819.html). Good luck.

**Comment by usmansani123** [comment]
I am well versed with C++, Java, R, Scala, and Python.  First I have already removed the errors but the code is still not working then I have shared it with you.I have also removed syntax errors in this code like the initialization of the 2D array is not correct etc.These errors are in header files of the code. I have changed the code but the file is still not working.

**Comment by wenquan** [comment]
@usmansani123 Which branch you are testing?

**Comment by usmansani123** [comment]
Dear sir, i have removed most of errors in the blits code. i have try my best to remove errors in the recent code from 3 weeks and most of errors have solved. i am trying to test the dummy video for running the main ( ) function code. May be Due to this reason, errors generates. Now, i need the testing video of zebrafish. so i can further test the code. Thnx.

**Comment by CrickCrick** [comment]
> Dear sir, i have removed most of errors in the blits code. i have try my best to remove errors in the recent code from 3 weeks and most of errors have solved. i am trying to test the dummy video for running the main ( ) function code. May be Due to this reason, errors generates. Now, i need the testing video of zebrafish. so i can further test the code. Thnx.

The branch you're testing is the one used to test the projector. All you need to run the code in main( ) is a projector (or a second screen). The overall test version maybe I'll upload in a few days. If you need the video, can I share it via Google drive to you? Thanks.

**Comment by usmansani123** [comment]
@wenquan @CrickCrick @young24 
Dear sir, I have found the fish video and solved all errors of our blitz code.
Thank you so much to all for your help and support.
