### ISSUE TITLE
Data Hierarchy (based on class)

### ISSUE THREAD

**Issue by young24** [Wenlab/BLITZ#4]
Whether this Class-in-Class data structure the best practice?
![image](https://user-images.githubusercontent.com/13465279/42125083-58b6ccc0-7ca2-11e8-9973-2eab8abf0f78.png)

**Comment by WanzhuoShi** [comment]
I am trying to make a relation legend, but I don't know which form is proper. So I make a diagram first. Can you give me some advice? Thanks in advance.
@young24 
![image](https://user-images.githubusercontent.com/41030651/45031025-4a151c00-b080-11e8-91ea-df729c0a6e59.png)

**Comment by WanzhuoShi** [comment]
This is just a sketch, I think write some brief functional description into the diagram may be better.

**Comment by young24** [comment]
A nice try. 👍 
It might be better to have some follow-up slides to explain the details of each class.

**Comment by WanzhuoShi** [comment]
Thank you. Writing all details in one diagram may looks messy. Making some follow-up slides is a better choice.

**Comment by WanzhuoShi** [comment]
I have completed the first part of the lab meeting PPT. The manuscript is on the desktop of your computer. If you have time, I hope to get some advice from you. Thanks in advance.
@young24

**Comment by young24** [comment]
Sure. Could you please put the PPT file into Nutstore's "Results" folder? So I can add some comments directly to the file. Thank you.
@WanzhuoShi

**Comment by WanzhuoShi** [comment]
I have put it into the folder. Thank you for your help.  
@young24

**Comment by young24** [comment]
I added some comments on the slides. However, the part 2 seems irrelevant with the lab meeting. You may need to check that. @WanzhuoShi

**Comment by WanzhuoShi** [comment]
I have finished most of the slides, but I am not very satisfied with the remarks now. I will modify it tonight. By the way, should the work flow of the real system be introduced?
@young24

**Comment by young24** [comment]
It's up to you, however, keep it concise if added.
@WanzhuoShi

**Comment by WanzhuoShi** [comment]
Okay, thank you.

**Comment by WanzhuoShi** [comment]
I have finished it. However, there is a little problem about proper expression in English, and I left a comment in Chinese to describe it for you. Could you please take a final check? Thanks.
@young24

**Comment by young24** [comment]
Ok, I'll check that.
@WanzhuoShi

**Comment by WanzhuoShi** [comment]
Thank you so much.
