### ISSUE TITLE
GLFW version 不统一

### ISSUE THREAD

**Issue by WanzhuoShi** [Wenlab/BLITZ#5]
当前的GLFW version 为3.2.1，安装教程中版本要求为3.0，请问师兄使用目前的这个版本也可以吗?
@young24

**Comment by young24** [comment]
You can try it, however, there is no guarantee that the new version would work. 
Another thing I want to remind you is that you don't have to run the code. Just read it and understand the structure of the ExperimentData Class. @WanzhuoShi

**Comment by WanzhuoShi** [comment]
好的，如果这样的话我就不安装了，直接读code，以后需要的话再安装
