### ISSUE TITLE
编译未能通过，可能是相机未配置好

### ISSUE THREAD

**Issue by WanzhuoShi** [Wenlab/BLITZ#6]
第一次编译失败，显示的错误信息为talk2camera.h(32): fatal error C1083: 无法打开包括文件:“pylon/PylonIncludes.h”: No such file or directory
![image](https://user-images.githubusercontent.com/41030651/44035499-3f776f0e-9f42-11e8-8e41-f4b63309ef1b.png)
应当是没有进行相机的配置，但是我在网上并没有找到配置pylon的教程。

此外，将clone到本地的源码文件转移到VS中成为一个Project的方式是配置好环境后，将文件夹中所有文件均拷贝至项目文件夹中，并全部添加至项目中吗？比如这个样子是正确的吗？
![image](https://user-images.githubusercontent.com/41030651/44035409-06b7ca88-9f42-11e8-9014-0123c0601c13.png)
需要师兄的帮助
@young24

**Comment by young24** [comment]
Please check this [link](https://www.baslerweb.com/fp-1476182890/media/downloads/documents/application_notes/AW00136801000_Getting_Started_with_pylon5_and_OpenCV.pdf) to get started with Pylon and OpenCV.

**Comment by WanzhuoShi** [comment]
刚刚完成了pylon的配置，在网上找了一个例程运行正常，还需要检验BLITZ能否正常运行吗？
@young24

**Comment by young24** [comment]
先不用了，你先尝试写一下详细的安装教程吧，新建一个branch，然后pull request就行。
