### ISSUE TITLE
make a code block into function

### ISSUE THREAD

**Issue by WanzhuoShi** [Wenlab/BLITZ#8]
Would you please send me a video? I can use this video to check my configuration and try to make that block into function. Thank you so much.
@young24

**Comment by WanzhuoShi** [comment]
And I have a question: are the videos which have been saved the same as real-time shooting videos?

**Comment by young24** [comment]
Can you access our server? At "\\222.195.69.205\wenlab\Young\Visual Modality may Affect Operant Learning Effect\OL_EXP_DATA\Pure_black (CS) versus pure_gray (NCS)\Huc_h2b_GCaMP6f", pick one .avi video as you like. @WanzhuoShi

**Comment by WanzhuoShi** [comment]
How can I access this server?

**Comment by young24** [comment]
Please come to me, I'll teach you.

**Comment by WanzhuoShi** [comment]
I annotate a lot of the code and establish a function. The MOG tracking block seems like running normally in the  prepare period but abnormally in the runOLexp function now. Would you like to check my code? Or I paste my code here?
@young24

**Comment by young24** [comment]
Sure, just upload your code to your branch and open a pull request. @WanzhuoShi

**Comment by WanzhuoShi** [comment]
Pull request has been merged.
